from __future__ import annotations

from dataclasses import dataclass, field
from statistics import mean
from typing import Any

from cv_adapter import CV_ADAPTER
from models import now_utc


@dataclass
class CameraBrainProfile:
    trained: bool = False
    trained_at: str | None = None
    samples_seen: int = 0
    avg_people_per_camera: float = 0.0
    avg_staff_ratio: float = 0.0
    avg_line_crossings: float = 0.0
    zone_baselines: dict[str, float] = field(default_factory=dict)


class CentralCameraBrain:
    """Fuses all camera metadata into one restaurant-level operating signal."""

    def __init__(self) -> None:
        self.profile = CameraBrainProfile()
        self.last_analysis: dict[str, Any] = {}

    def train_from_videos(self, feeds: list[dict[str, Any]], epochs: int = 4) -> dict[str, Any]:
        samples = []
        zone_people: dict[str, list[int]] = {}
        for epoch in range(max(1, epochs)):
            for feed in feeds:
                result = CV_ADAPTER.analyze(f"{feed['video_url']}#epoch={epoch}", feed["id"])
                result["zone"] = feed.get("zone", "Unknown")
                samples.append(result)
                zone_people.setdefault(result["zone"], []).append(result["people_count"])

        staff_ratios = [sample["staff_count"] / max(1, sample["people_count"]) for sample in samples]
        self.profile = CameraBrainProfile(
            trained=True,
            trained_at=now_utc().isoformat(),
            samples_seen=len(samples),
            avg_people_per_camera=round(mean([sample["people_count"] for sample in samples]), 2),
            avg_staff_ratio=round(mean(staff_ratios), 2),
            avg_line_crossings=round(mean([sample["line_crossings"] for sample in samples]), 2),
            zone_baselines={zone: round(mean(values), 2) for zone, values in zone_people.items()},
        )
        return self.status()

    def analyze_all(self, feeds: list[dict[str, Any]]) -> dict[str, Any]:
        camera_results = []
        for feed in feeds:
            result = CV_ADAPTER.analyze(feed["video_url"], feed["id"])
            result["name"] = feed["name"]
            result["zone"] = feed.get("zone", "Unknown")
            result["role"] = feed.get("role", "general")
            camera_results.append(result)

        total_people = sum(item["people_count"] for item in camera_results)
        total_staff = sum(item["staff_count"] for item in camera_results)
        total_guests = sum(item["guest_count"] for item in camera_results)
        crossings = sum(item["line_crossings"] for item in camera_results)
        zone_load = {}
        for item in camera_results:
            zone_load[item["zone"]] = zone_load.get(item["zone"], 0) + item["people_count"]

        baseline = max(1, self.profile.avg_people_per_camera * max(1, len(camera_results)))
        load_ratio = total_people / baseline if self.profile.trained else total_people / max(1, len(camera_results) * 6)
        if load_ratio >= 1.35 or crossings >= 7:
            status = "OVERLOADED"
        elif load_ratio >= 0.9 or crossings >= 4:
            status = "BUSY"
        else:
            status = "NORMAL"

        recommendations = []
        if total_staff / max(1, total_people) < max(0.12, self.profile.avg_staff_ratio * 0.65):
            recommendations.append("Staff coverage appears low relative to guests; assign runner or floor support.")
        if zone_load.get("Kitchen", 0) >= 6:
            recommendations.append("Kitchen camera load is high; watch for ticket delays.")
        if crossings >= 4:
            recommendations.append("Entrance/service movement is high; prioritize seating and cleaning flow.")
        if not recommendations:
            recommendations.append("Camera brain sees stable flow across zones.")

        self.last_analysis = {
            "trained": self.profile.trained,
            "status": status,
            "load_ratio": round(load_ratio, 2),
            "total_people": total_people,
            "total_staff": total_staff,
            "total_guests": total_guests,
            "line_crossings": crossings,
            "zone_load": zone_load,
            "camera_results": camera_results,
            "recommendations": recommendations,
            "analyzed_at": now_utc().isoformat(),
        }
        return self.last_analysis

    def status(self) -> dict[str, Any]:
        return {
            "profile": self.profile.__dict__,
            "last_analysis": self.last_analysis,
            "truth_note": "This central brain is trained/calibrated from video metadata generated by the local CV adapter. Replace CV_ADAPTER with YOLO/ByteTrack for true pixel-level inference.",
        }


CAMERA_BRAIN = CentralCameraBrain()
