from __future__ import annotations

import json
import os
import pickle
from pathlib import Path
from typing import Any

from sqlalchemy import bindparam, create_engine, text
from sqlalchemy.engine import Engine

from models import RestaurantState, now_utc


DB_PATH = Path(__file__).with_name("restaurant_os.sqlite3")


def database_url() -> str:
    return os.getenv("DATABASE_URL") or f"sqlite:///{DB_PATH.as_posix()}"


def make_engine() -> Engine:
    url = database_url()
    connect_args = {"check_same_thread": False} if url.startswith("sqlite") else {}
    return create_engine(url, connect_args=connect_args, pool_pre_ping=True, future=True)


ENGINE = make_engine()


def is_postgres() -> bool:
    return ENGINE.dialect.name == "postgresql"


def init_db() -> None:
    snapshot_blob_type = "BYTEA" if is_postgres() else "BLOB"
    audit_id_type = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if is_postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT"

    statements = [
        f"""
        CREATE TABLE IF NOT EXISTS snapshots (
            id INTEGER PRIMARY KEY CHECK (id = 1),
            state_blob {snapshot_blob_type} NOT NULL,
            updated_at TEXT NOT NULL
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS audit_log (
            id {audit_id_type},
            event_type TEXT NOT NULL,
            actor TEXT NOT NULL,
            payload TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS connectors (
            id TEXT PRIMARY KEY,
            provider TEXT NOT NULL,
            name TEXT NOT NULL,
            endpoint TEXT NOT NULL,
            enabled INTEGER NOT NULL,
            secret TEXT NOT NULL,
            last_status TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS task_workflow (
            task_id TEXT PRIMARY KEY,
            status TEXT NOT NULL,
            staff_id TEXT,
            updated_at TEXT NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS settings (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """,
    ]
    with ENGINE.begin() as conn:
        for statement in statements:
            conn.execute(text(statement))


def execute(statement: str, params: dict[str, Any] | None = None) -> None:
    with ENGINE.begin() as conn:
        conn.execute(text(statement), params or {})


def save_state(state: RestaurantState) -> None:
    execute(
        """
        INSERT INTO snapshots (id, state_blob, updated_at)
        VALUES (1, :state_blob, :updated_at)
        ON CONFLICT(id) DO UPDATE SET state_blob=excluded.state_blob, updated_at=excluded.updated_at
        """,
        {"state_blob": pickle.dumps(state), "updated_at": now_utc().isoformat()},
    )


def load_state() -> RestaurantState | None:
    with ENGINE.connect() as conn:
        row = conn.execute(text("SELECT state_blob FROM snapshots WHERE id = 1")).mappings().fetchone()
    if not row:
        return None
    try:
        blob = row["state_blob"]
        if isinstance(blob, memoryview):
            blob = blob.tobytes()
        return pickle.loads(blob)
    except Exception:
        return None


def audit(event_type: str, payload: dict[str, Any], actor: str = "system") -> None:
    execute(
        "INSERT INTO audit_log (event_type, actor, payload, created_at) VALUES (:event_type, :actor, :payload, :created_at)",
        {
            "event_type": event_type,
            "actor": actor,
            "payload": json.dumps(payload, default=str),
            "created_at": now_utc().isoformat(),
        },
    )


def recent_audit(limit: int = 80) -> list[dict[str, Any]]:
    with ENGINE.connect() as conn:
        rows = conn.execute(
            text("SELECT * FROM audit_log ORDER BY id DESC LIMIT :limit"),
            {"limit": limit},
        ).mappings().fetchall()
    return [
        {
            "id": row["id"],
            "event_type": row["event_type"],
            "actor": row["actor"],
            "payload": json.loads(row["payload"]),
            "created_at": row["created_at"],
        }
        for row in rows
    ]


def upsert_connector(config: dict[str, Any]) -> dict[str, Any]:
    connector_id = config.get("id") or f"{config.get('provider', 'connector')}-01"
    row = {
        "id": connector_id,
        "provider": config.get("provider", "custom"),
        "name": config.get("name", connector_id),
        "endpoint": config.get("endpoint", ""),
        "enabled": 1 if config.get("enabled", True) else 0,
        "secret": config.get("secret", ""),
        "last_status": config.get("last_status", "configured"),
        "updated_at": now_utc().isoformat(),
    }
    execute(
        """
        INSERT INTO connectors (id, provider, name, endpoint, enabled, secret, last_status, updated_at)
        VALUES (:id, :provider, :name, :endpoint, :enabled, :secret, :last_status, :updated_at)
        ON CONFLICT(id) DO UPDATE SET
          provider=excluded.provider,
          name=excluded.name,
          endpoint=excluded.endpoint,
          enabled=excluded.enabled,
          secret=excluded.secret,
          last_status=excluded.last_status,
          updated_at=excluded.updated_at
        """,
        row,
    )
    audit("connector_saved", {"id": connector_id, "provider": row["provider"], "enabled": bool(row["enabled"])})
    return public_connector(row)


def list_connectors() -> list[dict[str, Any]]:
    with ENGINE.connect() as conn:
        rows = conn.execute(text("SELECT * FROM connectors ORDER BY updated_at DESC")).mappings().fetchall()
    return [public_connector(dict(row)) for row in rows]


def public_connector(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": row["id"],
        "provider": row["provider"],
        "name": row["name"],
        "endpoint": row["endpoint"],
        "enabled": bool(row["enabled"]),
        "secret_set": bool(row["secret"]),
        "last_status": row["last_status"],
        "updated_at": row["updated_at"],
    }


def set_task_status(task_id: str, status: str, staff_id: str | None = None) -> dict[str, Any]:
    execute(
        """
        INSERT INTO task_workflow (task_id, status, staff_id, updated_at)
        VALUES (:task_id, :status, :staff_id, :updated_at)
        ON CONFLICT(task_id) DO UPDATE SET status=excluded.status, staff_id=excluded.staff_id, updated_at=excluded.updated_at
        """,
        {"task_id": task_id, "status": status, "staff_id": staff_id, "updated_at": now_utc().isoformat()},
    )
    audit("task_workflow", {"task_id": task_id, "status": status, "staff_id": staff_id})
    return {"task_id": task_id, "status": status, "staff_id": staff_id}


def materialize_tasks(tasks: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    current_time = now_utc().isoformat()
    task_ids = [task["id"] for task in tasks]
    with ENGINE.begin() as conn:
        for task in tasks:
            existing = conn.execute(
                text("SELECT status, staff_id FROM task_workflow WHERE task_id = :task_id"),
                {"task_id": task["id"]},
            ).mappings().fetchone()
            status = existing["status"] if existing else "NEW"
            staff_id = existing["staff_id"] if existing and existing["staff_id"] else task.get("assigned_staff_id")
            conn.execute(
                text(
                    """
                    INSERT INTO task_workflow (task_id, status, staff_id, updated_at)
                    VALUES (:task_id, :status, :staff_id, :updated_at)
                    ON CONFLICT(task_id) DO UPDATE SET
                      staff_id=COALESCE(task_workflow.staff_id, excluded.staff_id),
                      updated_at=excluded.updated_at
                    """
                ),
                {"task_id": task["id"], "status": status, "staff_id": staff_id, "updated_at": current_time},
            )
        if task_ids:
            statement = text(
                """
                UPDATE task_workflow
                SET status = 'EXPIRED', updated_at = :updated_at
                WHERE status NOT IN ('DONE', 'EXPIRED') AND task_id NOT IN :task_ids
                """
            ).bindparams(bindparam("task_ids", expanding=True))
            conn.execute(statement, {"updated_at": current_time, "task_ids": task_ids})
    return task_status_map()


def task_status_map() -> dict[str, dict[str, Any]]:
    with ENGINE.connect() as conn:
        rows = conn.execute(text("SELECT * FROM task_workflow")).mappings().fetchall()
    return {
        row["task_id"]: {
            "status": row["status"],
            "staff_id": row["staff_id"],
            "updated_at": row["updated_at"],
        }
        for row in rows
    }


DEFAULT_SLA = {
    "seat_wait_max_min": 8,
    "order_wait_max_min": 7,
    "food_wait_max_min": 18,
    "dirty_table_max_min": 8,
    "critical_task_score": 115,
}


def get_settings(key: str, default: Any = None) -> Any:
    with ENGINE.connect() as conn:
        row = conn.execute(text("SELECT value FROM settings WHERE key = :key"), {"key": key}).mappings().fetchone()
    if not row:
        return default
    return json.loads(row["value"])


def set_settings(key: str, value: Any) -> Any:
    execute(
        """
        INSERT INTO settings (key, value, updated_at) VALUES (:key, :value, :updated_at)
        ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at
        """,
        {"key": key, "value": json.dumps(value), "updated_at": now_utc().isoformat()},
    )
    audit("settings_updated", {"key": key, "value": value}, actor="manager")
    return value


def get_sla_settings() -> dict[str, Any]:
    saved = get_settings("sla", DEFAULT_SLA)
    return {**DEFAULT_SLA, **saved}


init_db()
